from pydantic import BaseModel, Field, field_validator, model_validator
from datetime import datetime, timezone
from typing import Optional
from enum import Enum


class AlertLevel(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    NORMAL = "NORMAL"
    REJECTED = "REJECTED"


class RecommendedAction(str, Enum):
    IMMEDIATE_RESPONSE = "immediate_response"
    URGENT_REVIEW = "urgent_review"
    CLINICIAN_REVIEW = "clinician_review"
    OBSERVATION = "observation"


# ── Input ─────────────────────────────────────────────────────────────────────

class VitalsSnapshotInput(BaseModel):
    """Incoming vitals snapshot from monitoring device or mock producer."""

    patient_id: str = Field(..., description="Unique patient identifier")
    systolic_bp: float = Field(..., description="Systolic blood pressure in mmHg")
    diastolic_bp: float = Field(..., description="Diastolic blood pressure in mmHg")
    heart_rate: float = Field(..., description="Heart rate in beats per minute")
    spo2: float = Field(..., description="Peripheral oxygen saturation as percentage")
    snapshot_timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp of the vitals reading"
    )

    @field_validator("systolic_bp")
    @classmethod
    def validate_sbp(cls, v: float) -> float:
        if not (40 <= v <= 300):
            raise ValueError(f"Systolic BP {v} is outside physiologically plausible range (40–300 mmHg)")
        return v

    @field_validator("diastolic_bp")
    @classmethod
    def validate_dbp(cls, v: float) -> float:
        if not (20 <= v <= 200):
            raise ValueError(f"Diastolic BP {v} is outside physiologically plausible range (20–200 mmHg)")
        return v

    @field_validator("heart_rate")
    @classmethod
    def validate_hr(cls, v: float) -> float:
        if not (1 <= v <= 300):
            raise ValueError(f"Heart rate {v} is outside physiologically plausible range (1–300 bpm)")
        return v

    @field_validator("spo2")
    @classmethod
    def validate_spo2(cls, v: float) -> float:
        if not (50 <= v <= 100):
            raise ValueError(f"SpO2 {v} is outside physiologically plausible range (50–100%)")
        return v

    @model_validator(mode="after")
    def validate_sbp_gt_dbp(self) -> "VitalsSnapshotInput":
        if self.systolic_bp <= self.diastolic_bp:
            raise ValueError(
                f"Systolic BP ({self.systolic_bp}) must be greater than Diastolic BP ({self.diastolic_bp})"
            )
        return self


# ── Clinical Scores ────────────────────────────────────────────────────────────

class NEWS2Breakdown(BaseModel):
    sbp_score: int
    dbp_score: int
    heart_rate_score: int
    spo2_score: int
    total_score: int
    any_single_critical: bool  # True if any individual score is 3


class QSOFABreakdown(BaseModel):
    sbp_flag: bool   # SBP ≤ 100
    hr_flag: bool    # HR > 90
    spo2_flag: bool  # SpO2 < 94% (proxy for respiratory dysfunction)
    score: int
    high_risk: bool  # score >= 2


# ── Output ────────────────────────────────────────────────────────────────────

class AlertResponse(BaseModel):
    alert_id: str
    patient_id: str
    snapshot_id: str
    alert_level: AlertLevel
    news2: NEWS2Breakdown
    qsofa: QSOFABreakdown
    sepsis_risk_flag: bool
    recommended_action: RecommendedAction

    # LLM reasoning — present if Ollama was available
    reasoning_summary: Optional[str] = Field(
        None,
        description="Plain-English summary of why this alert level was assigned"
    )
    contributing_factors: Optional[list[str]] = Field(
        None,
        description="Key risk factors from the patient EHR that influenced the assessment"
    )
    llm_confidence: Optional[float] = None
    llm_limitations: Optional[str] = None
    rule_based_only: bool = Field(
        False,
        description="True if LLM was unavailable and only rule-based scoring was used"
    )

    disclaimer: str = (
        "CLINICAL DECISION SUPPORT ONLY. This output is generated by an AI system "
        "and must not replace the clinical judgment of a qualified healthcare professional. "
        "All alerts require clinical review before action is taken."
    )
    created_at: datetime


class AlertListItem(BaseModel):
    alert_id: str
    patient_id: str
    alert_level: AlertLevel
    news2_score: int
    qsofa_score: int
    sepsis_risk_flag: bool
    recommended_action: RecommendedAction
    rule_based_only: bool
    created_at: datetime


class PatientSummary(BaseModel):
    patient_id: str
    age: Optional[int]
    gender: Optional[str]
    ehr_ingested: bool
    total_snapshots: int
    total_alerts: int
    last_alert_level: Optional[AlertLevel]
    last_snapshot_at: Optional[datetime]


class HealthStatus(BaseModel):
    status: str
    ollama: str
    chromadb: str
    database: str
    guardrails: str
