"""
Output guardrails — evaluator gate between LLM output and the alert router.

Checks:
1. Schema enforcement  — LLM returned required fields
2. Grounding check     — reasoning references actual vital values
3. Prohibited content  — no drug names, doses, or direct treatment orders
4. Confidence check    — low confidence flagged for human review
5. Contradiction check — LLM level must not differ from rule level by > 1 tier
6. Disclaimer enforce  — mandatory disclaimer present in every output
"""

from __future__ import annotations
import re
from dataclasses import dataclass, field
from vitals.schemas import AlertLevel, VitalsSnapshotInput

# Alert level ordering for contradiction check
ALERT_ORDER = {
    AlertLevel.NORMAL: 0,
    AlertLevel.MEDIUM: 1,
    AlertLevel.HIGH: 2,
    AlertLevel.CRITICAL: 3,
}

# Prohibited patterns — drug names, dosing language.
# NOTE: stems use \w* so inflected forms are caught too. A bare "\bstem\b"
# does NOT match "stem"+suffix, which previously let intubation/defibrillation/
# prescribing through untouched.
PROHIBITED_PATTERNS = [
    r"\b\d+(?:\.\d+)?\s*(?:mg|mcg|\u00b5g|ug|ml|g|units?|iu)\b",   # dosing
    r"\badminister\w*\b",                    # administer/-s/-ed/-ing
    r"\badministration\b",                   # (not a suffix of "administer")
    r"\bprescrib\w*\b",                      # prescribe/-s/-d/-ing
    r"\bprescription\b",
    r"\binfus\w*\b",                         # infuse/-d/-ing/infusion
    r"\bbolus\w*\b",                         # bolus/boluses
    r"\bnorepinephrine\b", r"\bvasopressin\b", r"\bdopamine\b",
    r"\bvancomycin\b", r"\bpiperacillin\b", r"\bmeropenem\b",
    r"\bintubat\w*\b",                       # intubate/-d/intubation
    r"\bdefibrillat\w*\b",                   # defibrillate/-d/defibrillation
]

DISCLAIMER = (
    "CLINICAL DECISION SUPPORT ONLY. This output is generated by an AI system "
    "and must not replace the clinical judgment of a qualified healthcare professional. "
    "All alerts require clinical review before action is taken."
)


@dataclass
class CheckResult:
    """Outcome of one guardrail check."""
    passed: bool
    reason: str | None = None


@dataclass
class OutputValidationResult:
    valid: bool
    sanitized_reasoning: str | None
    confidence: float | None
    flag_for_human_review: bool
    rejection_reason: str | None
    # Per-check breakdown. Always contains all four keys:
    # "schema", "grounding", "prohibited", "contradiction".
    checks: dict[str, CheckResult] = field(default_factory=dict)
    disclaimer: str = DISCLAIMER


def _vital_forms(value: float) -> set[str]:
    """Accepted written forms of one vital value (e.g. 98.0 -> {"98", "98.0"})."""
    fv = float(value)
    if fv.is_integer():
        return {str(int(fv)), f"{int(fv)}.0"}
    return {f"{fv:g}", f"{fv:.1f}"}


def _mentions_value(text: str, value: float) -> bool:
    """
    True if `text` cites this exact vital value, written naturally
    ("98", "98%", "98 %", "98.0").

    Deliberately strict about the NUMBER: a different value (88), a near-miss
    (98.5) or a value embedded in a larger number (1980) must NOT count.
    """
    for form in _vital_forms(value):
        if re.search(r"(?<![\d.])" + re.escape(form) + r"(?!\.?\d)", text):
            return True
    return False


def _is_grounded(reasoning: str, snapshot: VitalsSnapshotInput) -> bool:
    return any(
        _mentions_value(reasoning, v)
        for v in (snapshot.systolic_bp, snapshot.diastolic_bp,
                  snapshot.heart_rate, snapshot.spo2)
    )


def _first_prohibited(reasoning: str) -> str | None:
    for pattern in PROHIBITED_PATTERNS:
        if re.search(pattern, reasoning, re.IGNORECASE):
            return pattern
    return None


def validate_llm_output(
    llm_output: dict,
    rule_alert_level: AlertLevel,
    snapshot: VitalsSnapshotInput,
    min_confidence: float = 0.6,
) -> OutputValidationResult:
    """
    Validates and sanitizes the structured JSON output from MedGemma.

    ALL four checks are evaluated on every call — there is no early return —
    so `result.checks` is always a complete per-check breakdown. This is what
    lets the same function filter teacher training data and score the student.

    `valid`, `rejection_reason`, `confidence`, `sanitized_reasoning` and
    `flag_for_human_review` keep their original meanings for existing callers.
    """
    checks: dict[str, CheckResult] = {}

    # 1. Schema — required fields present
    required = {"risk_level", "confidence", "reasoning", "sepsis_risk_flag"}
    missing = required - set(llm_output.keys())
    checks["schema"] = CheckResult(
        passed=not missing,
        reason=f"LLM output missing required fields: {missing}" if missing else None,
    )

    reasoning: str = str(llm_output.get("reasoning", ""))
    try:
        confidence: float = float(llm_output.get("confidence", 0.0))
    except (TypeError, ValueError):
        confidence = 0.0

    # 2. Grounding — reasoning cites at least one real vital value
    grounded = _is_grounded(reasoning, snapshot)
    checks["grounding"] = CheckResult(
        passed=grounded,
        reason=None if grounded else
        "LLM reasoning does not reference any provided vital values (grounding failure).",
    )

    # 3. Prohibited content — no drugs, doses or treatment orders
    hit = _first_prohibited(reasoning)
    checks["prohibited"] = CheckResult(
        passed=hit is None,
        reason=None if hit is None else
        f"LLM output contains prohibited clinical content (matched: {hit}).",
    )

    # 4. Contradiction — LLM level within 1 tier of the rule level
    try:
        llm_level = AlertLevel(llm_output["risk_level"])
    except (KeyError, ValueError):
        checks["contradiction"] = CheckResult(
            passed=False,
            reason=f"LLM returned unknown risk_level: {llm_output.get('risk_level')}",
        )
    else:
        level_diff = abs(ALERT_ORDER[llm_level] - ALERT_ORDER[rule_alert_level])
        checks["contradiction"] = CheckResult(
            passed=level_diff <= 1,
            reason=None if level_diff <= 1 else (
                f"LLM alert level ({llm_level}) contradicts rule-based level "
                f"({rule_alert_level}) by {level_diff} tiers (max allowed: 1)."
            ),
        )

    valid = all(c.passed for c in checks.values())
    # First failure in check order — preserves the original rejection messages.
    rejection_reason = next((c.reason for c in checks.values() if not c.passed), None)

    return OutputValidationResult(
        valid=valid,
        sanitized_reasoning=_strip_thinking_tokens(reasoning).strip() if valid else None,
        # original returned None when the schema check was the failure
        confidence=confidence if checks["schema"].passed else None,
        flag_for_human_review=True if not valid else confidence < min_confidence,
        rejection_reason=rejection_reason,
        checks=checks,
    )


def _strip_thinking_tokens(text: str) -> str:
    """Remove Gemma 3 internal thinking tokens from LLM output."""
    # Remove <unused94>...</unused95> thinking blocks
    text = re.sub(r"<unused94>.*?<unused95>", "", text, flags=re.DOTALL)
    # Remove any other leftover unused tokens
    text = re.sub(r"<unused\d+>", "", text)
    return text.strip()
